sudo: required
dist: trusty
before_install:
# - chmod +x tlsetup.sh 
# - ./tlsetup.sh
- sudo apt-get -qq update
- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-xetex
# - sudo apt-get install -y xzdec
# - sudo apt-get install -y biber
- sudo tlmgr init-usertree
- sudo tlmgr option repository ftp://tug.org/historic/systems/texlive/2017/tlnet-final
# - sudo tlmgr install \
#     hyperref       \
#     parskip        \
#     babel          \
#     tools          \
#     graphics       \
#     xcolor

script:
# - make clean
# - make latex PROJECT=$FILE_NAME BUILDDIR=_build COMPILER=xelatex
# - ./dropbox_uploader.sh upload _build/main.pdf ${TRAVIS_BRANCH}/main-latest.pdf
# - ./dropbox_uploader.sh upload _build/main.pdf ${TRAVIS_BRANCH}/main-${TRAVIS_JOB_NUMBER}.pdf
  - mkdir _build
  - xelatex -interaction=nonstopmode -halt-on-error -output-directory=_build 132-494-F18C-500.tex

# after_success:
#   - git config --global user.email "github@hoelweb.com"
#   - git config --global user.name "jkhoel"
#   - git checkout -b master
#   - git add . *.pdf
#   - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
#   - git remote add origin-pages https://${GH_TOKEN}@github.com/MVSE-outreach/resources.git > /dev/null 2>&1
#   - git push --quiet --set-upstream origin-pages gh-pages 

before_deploy:
  - git config --local user.name "jkhoel"
  - git config --local user.email "github@hoelweb.com"
  - git tag "$FILE_NAME-$TRAVIS_BUILD_NUMBER"
  
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: _build/*.pdf
  skip_cleanup: true

after_deploy:
  - rm -rf _build