sudo: required
dist: trusty
before_install:
  - ls -ln
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-xetex
  - sudo apt-get install -y xzdec
  - sudo apt-get install -y biber
  - sudo tlmgr init-usertree
  - sudo tlmgr option repository ftp://tug.org/historic/systems/texlive/2017/tlnet-final
  - sudo apt-get install fonts-lmodern
  - sudo fc-cache -fv

script:
  - mkdir _build
  - xelatex -interaction=nonstopmode -halt-on-error -output-directory=_build 132-494-F18C-500.tex

before_deploy:
  - git config --local user.name "jkhoel"
  - git config --local user.email "github@hoelweb.com"
  - git tag "$FILE_NAME (Build $TRAVIS_BUILD_NUMBER)"
  
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file: _build/$FILE_NAME.pdf
  skip_cleanup: true

after_deploy:
  - rm -rf _build


# xelatex -interaction=nonstopmode -halt-on-error -output-directory=_build 132-494-F18C-500.tex